apiVersion: v1
kind: Service
metadata:
  name: sdap-cassandra
spec:
  clusterIP: None
  ports:
  - name: cql
    port: 9042
    targetPort: cql
  selector:
    app: sdap-cassandra

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra-set
spec:
  serviceName: sdap-cassandra
  replicas: {{ .Values.cassandra.replicas }}
  selector:
    matchLabels:
      app: sdap-cassandra
  template:
    metadata:
      labels:
        app: sdap-cassandra
    spec:
      terminationGracePeriodSeconds: 120
      {{ if .Values.cassandra.tolerations }}
      tolerations:
{{ .Values.cassandra.tolerations | toYaml | indent 6 }}
      {{ end }}
      {{ if .Values.cassandra.nodeSelector }}
      nodeSelector:
{{ .Values.cassandra.nodeSelector | toYaml | indent 8 }}
      {{ end }}
      affinity:
        podAntiAffinity:
          # Prefer spreading over all hosts
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                      - sdap-cassandra
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: cassandra
        image: nexusjpl/cassandra:1.0.0-rc1
        imagePullPolicy: Always
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        resources:
          requests:
            cpu: {{ .Values.cassandra.requests.cpu }}
            memory: {{ .Values.cassandra.requests.memory }}
          limits:
            cpu: {{ .Values.cassandra.limits.cpu }}
            memory: {{ .Values.cassandra.limits.memory }}
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - nodetool drain
        env:
          - name: MAX_HEAP_SIZE
            value: 2G
          - name: HEAP_NEWSIZE
            value: 200M
          - name: CASSANDRA_SEEDS
            value: "cassandra-set-0.sdap-cassandra"
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        volumeMounts:
        - name: cassandra-data
          mountPath: /var/lib/cassandra

  volumeClaimTemplates:
  - metadata:
      name: cassandra-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.storageClass }}
      resources:
        requests:
          storage: {{ .Values.cassandra.storage }}
