apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: history-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ .Values.storageClass }}

